title: Pig30nidaE's Blog
description: "이것 저것 기록하는 블로그"
author:
  name: "Pig30nidaE"
  email: "nope"
  url: "https://Pig30nidaE/github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

menu:
  - title: 42Seoul
    url:   /42Seoul/

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Optional. The default date format, used if none is specified in the tag.

# Custom variables
owner : "Pig30nidaE"
year : "2024"

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 5
paginate_path: "page:num"

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-TXE91ESESY"
    anonymize_ip         : # true, false (default)