title: Pig30nidaE's Blog
description: "이것 저것 기록하는 블로그"
author:
  name: "Pig30nidaE"
  email: "nope"
  url: "https://Pig30nidaE/github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

menu:
  - title: 42Seoul
    url:   /42Seoul/

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.

last-modified-at:
​    date-format: '%d-%b-%y' #(like "04-Jan-14").

# Custom variables
owner : "Pig30nidaE"
year : "2024"

#collections:
#  featured_categories:
#    permalink:         /:name/
#    output:            true
#  featured_tags:
#    permalink:         /tag-:name/
#    output:            true

#category_path: "category" # <- default value
#category_layout: "category.html" # <- default value

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 5
paginate_path: "page:num"

category_dir: "categories"
category_layout: "index.html"